// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfourkavzkxgkqirtmqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mb3Vya2F2emt4Z2txaXJ0bXFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5OTczOTgsImV4cCI6MjA3MzU3MzM5OH0.vw0B3iHZLuOHUl3GgFM59VGJuZ5pjjl853NT23kr2E4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});